int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int helper(int c, int i);
int is_prime_number(int n);
int _sqrt(int x, int i);
int helper2(int n, int d);